//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function for HiveCluster.
func (in *HiveCluster) DeepCopyInto(out *HiveCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of HiveCluster.
func (in *HiveCluster) DeepCopy() *HiveCluster {
	if in == nil {
		return nil
	}
	out := new(HiveCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *HiveCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function for HiveClusterSpec.
func (in *HiveClusterSpec) DeepCopyInto(out *HiveClusterSpec) {
	*out = *in
	if in.DefaultNodeSelector != nil {
		in, out := &in.DefaultNodeSelector, &out.DefaultNodeSelector
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for HiveClusterStatus.
func (in *HiveClusterStatus) DeepCopyInto(out *HiveClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for HiveClusterList.
func (in *HiveClusterList) DeepCopyInto(out *HiveClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *HiveClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy creates a deep copy of HiveClusterList.
func (in *HiveClusterList) DeepCopy() *HiveClusterList {
	if in == nil {
		return nil
	}
	out := new(HiveClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function for HiveCompany.
func (in *HiveCompany) DeepCopyInto(out *HiveCompany) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of HiveCompany.
func (in *HiveCompany) DeepCopy() *HiveCompany {
	if in == nil {
		return nil
	}
	out := new(HiveCompany)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *HiveCompany) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for HiveCompanySpec.
func (in *HiveCompanySpec) DeepCopyInto(out *HiveCompanySpec) {
	*out = *in
}

// DeepCopyInto for HiveCompanyStatus.
func (in *HiveCompanyStatus) DeepCopyInto(out *HiveCompanyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto for HiveCompanyList.
func (in *HiveCompanyList) DeepCopyInto(out *HiveCompanyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveCompany, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *HiveCompanyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy for HiveCompanyList.
func (in *HiveCompanyList) DeepCopy() *HiveCompanyList {
	if in == nil {
		return nil
	}
	out := new(HiveCompanyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for HiveWorkerPool.
func (in *HiveWorkerPool) DeepCopyInto(out *HiveWorkerPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy for HiveWorkerPool.
func (in *HiveWorkerPool) DeepCopy() *HiveWorkerPool {
	if in == nil {
		return nil
	}
	out := new(HiveWorkerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *HiveWorkerPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for HiveWorkerPoolSpec.
func (in *HiveWorkerPoolSpec) DeepCopyInto(out *HiveWorkerPoolSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources.Limits != nil {
		in, out := &in.Resources.Limits, &out.Resources.Limits
		*out = make(corev1.ResourceList, len(*in))
		for k, v := range *in {
			(*out)[k] = v.DeepCopy()
		}
	}
	if in.Resources.Requests != nil {
		in, out := &in.Resources.Requests, &out.Resources.Requests
		*out = make(corev1.ResourceList, len(*in))
		for k, v := range *in {
			(*out)[k] = v.DeepCopy()
		}
	}
	if in.AdapterConfig != nil {
		in, out := &in.AdapterConfig, &out.AdapterConfig
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

// DeepCopyInto for HiveWorkerPoolStatus.
func (in *HiveWorkerPoolStatus) DeepCopyInto(out *HiveWorkerPoolStatus) {
	*out = *in
	if in.SyncedAgentIDs != nil {
		in, out := &in.SyncedAgentIDs, &out.SyncedAgentIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto for HiveWorkerPoolList.
func (in *HiveWorkerPoolList) DeepCopyInto(out *HiveWorkerPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveWorkerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object.
func (in *HiveWorkerPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy for HiveWorkerPoolList.
func (in *HiveWorkerPoolList) DeepCopy() *HiveWorkerPoolList {
	if in == nil {
		return nil
	}
	out := new(HiveWorkerPoolList)
	in.DeepCopyInto(out)
	return out
}
